version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: task-tracker
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-network

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    networks:
#      - finance-network
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#    networks:
#      - finance-network

  task-service:
    build:
      context: ./task-service
    container_name: task-service
    env_file:
      - .env
    depends_on:
      - postgres
#      - kafka
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    ports:
      - "8080:8080"
#    volumes:
#      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - task-network

#  notification-service:
#    build:
#      context: ./notification-service
#    container_name: notification-service
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_MAIL_PASSWORD: ${GOOGLE_MAIL_PASSWORD}
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    ports:
#      - "8083:8083"
#    networks:
#      - finance-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8081:8081"
    networks:
      - task-network

volumes:
  postgres-data:

networks:
  task-network:
    driver: bridge
